global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter (system metrics)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["mahler:9100"]

  # Metrics from cAdvisor
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Metrics from the matrix-synapse
  - job_name: "matrix-synapse"
    static_configs:
      - targets: ["synapse-app:9000"]

  # Metrics from the satisfactory realtime monitoring
  - job_name: "satisfactory-monitoring"
    scrape_interval: 3m
    static_configs:
      - targets: ["mahler:9000"]
      # - targets: ["pterodactyl-frmcompanion:9000"]
