global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter (system metrics)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["mahler:9100"]

  # Metrics from the docker daemon
  - job_name: "docker"
    static_configs:
      - targets: ["mahler:9323"]

  # Metrics from the matrix-synapse
  - job_name: "matrix-synapse"
    static_configs:
      - targets: ["synapse-app:9000"]
    static_configs:
      - targets: ['mahler:9100']
    scrape_interval: 15s
